CONTAINER opipe
{
	NAME opipe;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL	PIPEOBJECT_RAD_OUTER								{ UNIT METER; MIN 0.0; STEP 0.1; }

		GROUP
		{
			COLUMNS 2;

			BOOL	PIPEOBJECT_USEINNER								{  }
			REAL	PIPEOBJECT_RAD_INNER							{ UNIT METER; MIN 0.0; STEP 0.1; }
		}

		SEPARATOR																	{ LINE; }

		LONG	PIPEOBJECT_PROFILE
		{
			CYCLE
			{
				PIPEOBJECT_PROFILE_CIRCLE;
				PIPEOBJECT_PROFILE_NSIDE;
			}
		}
		LONG	PIPEOBJECT_PROFILE_NSIDE_SIDES			{ MIN 3; }

		SEPARATOR																	{ LINE; }

		INCLUDE Ospline;
		LONG SPLINEOBJECT_TYPE										{ HIDDEN; }
		BOOL SPLINEOBJECT_CLOSED									{ HIDDEN; }
	}
}
