#ifndef _Opipe_H_
#define _Opipe_H_

enum
{
	PIPEOBJECT_RAD_OUTER						= 10001,
	PIPEOBJECT_RAD_INNER						= 10002,
	PIPEOBJECT_PROFILE							= 10003,
		PIPEOBJECT_PROFILE_CIRCLE				= 1,
		PIPEOBJECT_PROFILE_NSIDE				= 2,
	PIPEOBJECT_USEINNER							= 10004,
	PIPEOBJECT_PROFILE_NSIDE_SIDES	= 10005,
};

#endif
