enum
{
	// string table definitions
	IDS_PIPEOBJECT	= 10000,
	IDS_PIPEOBJECT_PROFILE_OUTER,
	IDS_PIPEOBJECT_PROFILE_INNER,
	IDS_PIPEOBJECT_CONNECTOBJ,

// End of symbol definition
  _DUMMY_ELEMENT_
};
